apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.imageName }}
  storage:
    size: {{ .Values.cluster.storageSize }}
    storageClass: {{ .Values.cluster.storageClass }}
  bootstrap:
    initdb:
      database: {{ .Values.cluster.database }}
      owner: {{ .Values.cluster.owner }}
      secret:
        name: {{ .Values.cluster.appSecret }}
  {{- if .Values.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.backup.retentionPolicy | quote }}
    barmanObjectStore:
      destinationPath: {{ .Values.backup.destinationPath }}
      endpointURL: {{ .Values.backup.endpointURL }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.backup.s3Secret }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.backup.s3Secret }}
          key: ACCESS_SECRET_KEY
  {{- end }}
