---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: event-exporter-discord
  namespace: monitoring
spec:
  encryptedData:
    url: AgAiloTIbTGioBngaRzXGKPS/IsQ9U6MyqlmJYWyPbnP+c7LJKh8w4gNhjhUOsjWHkYiL4EKZ8q9NbY4nAclbsgdG2yya3Zx2mypQrKYAWBqSYA3pomH+GckQk1DMmTDAXUeTTRZ4LTTJwcnCqXiblcJgdHIuTMicNIzOQ5AyN/Kvoh/NlXJBKdB/e73ZqGlc35SMroUKWNm1kbcNuKDH3LD8Jdge0Tm9wz9GenZFdcpwIrSfAv8tkf4peCgr66mvMwDoAJLdTc0X6QIcOpFiSLTLkCUXKZGQAHPGXq7bO/pm6vE5Fp6DkEykZW/XfE6CTyEOONmOBBJO7OjlbcuDzAIa3s50KePdElD2o0njAJUWUvVYuLY8WGrvWm/GdR9M1sbu0rILDkBYunZ6GwYFCd0HZd3A7e8w/0ToJTciyktRkETzqh1P4JJqwCaZI8YLXLIQT7tdhLpZJMe4lELg+OOgv/5Iau6olmNAUd5bhqbMCh/pc2TbqJyzBIScK02ukmfHyKafjtrDt+elki0Q3HEWfIlnk9VcvpZwjqLdACAXNzYkA11aWypLateIFPzXDkUBydYXDrUcNkH/LMAbn2/Aj8XI4B7PjZ04+Tz7SmzQ/6SUco9A5Typs9ZOCuKptSWeen+g9n2FAxi38KwBDrQr7o8DApAEYXNpQ7WQJddfQcXVkwWXCTpDtQVHulKrsQVjILXcOtFadzyCNpF4e4AQ2JxxYt3V84/tsSstJmP7HBOioCX1A22GAuNpa7r7oCwchOS2Qir/PO9oKPSWr6BylrSMsjP+YRzjzU0GhcAhmW36mIxNiMkjAgeZN1vxG9dxOT19zpIX0hamM/Z1wFUcBZkyLY9sgCu
  template:
    metadata:
      name: event-exporter-discord
      namespace: monitoring
    type: Opaque
