---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: event-exporter-discord
  namespace: monitoring
spec:
  encryptedData:
    url: AgBJGl4zAsldMGeG737mT35fnjPb4tMK+RLC1YeEvu9ACVirF+kvA3/Ug7DRUoZ3DLCsCSfkAFIOA+DNSqTRpMbKNCN0ODczBBDtu51X7vwufUC1W9m+40HONU6A5oBDfAfzwyFUpUl/2WfnsPE1lqgr0QB3UKW0KhprcZUpszVjW3k+5uHjXTX21Uba8hNFlBMvsVd31hLdHj48ZNSjnvqYktM6sNKoP8yC1jF8BwlE0m63vFk6Omurb1QhFzD+7uCRd/Hsr1c2giW1QhdGW2JZbQ+q8MbLeBUrxwwnI52NhUym6xiP5m71iCgAifIT0xVeY2CbwxpxY4g3Znx3hKgv0BWJI+ek/n3pGN4wtosSCDpVoHNFRuhWjt6WUPhVSdCY/D+hb7rolKJ+6tcCaB9sIBXyO+OeKty1Ddrl1jUtX+D/QoHj3gp+3l44+4r5ep3KdApYsyKi0LMlpnFqQKVoY2EuSOysbwD0DvOhptCuCrJw5t+hc+jimb9ibaPR9vSaFXv6xR3aXKXZ8Go4rX7u12FWr1NTYu2eRAD1dWLnnM+DQLNcsAu9rsxchU8Sfi+07c+Qz/QmCJkBYJfIe/R5yntCWS2Zqt9B9SpG4fWpLWp3kpArHhdfGRGKe91fn5HQhez8aJtFyf1ZFtWRBWP3f380QGUV7xZ9tKngJBzSG1eU9+yWFlV00StuXsSN9BkukDzI5MjQZFctTWQvoiSPCPIQk6M3+MMZqEfCJaPCQEoSRo01OH5BRZhxe25+HLc/8G0snp5EVPlCF4scG+P0dncIQfg032nv4XQgvpGBZZN9FTKp/he2+Kd9WbFWlBqw4R31hCMRaWFCwZLxmmdRNIJEOxv6okhC
  template:
    metadata:
      name: event-exporter-discord
      namespace: monitoring
    type: Opaque
