---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: barbu
spec:
  encryptedData:
    .dockerconfigjson: AgAaWnQKJhWupN/dCLK/FUHb7JcRR78P2OI3s5pvqTdWxCWrJbyIZ1Bq92S2jfUzdyRfFej/+Z5B14DknwmFogqlsmfQBQBNc2pGUznckjeM4xyIuP9Yjen4V40WsGwnScf64oVbBL9+Ma2oAm2e72kluXuZajqxOyO8cebqsp3o8d0X0rOV33hCyqx5MIpsLydVc2amiSml8nwmrtF/LN5WcFtBJMsquY5sU/emgV3afZOggnRgeG0jm04UedwrAHcmenRtAAA2StEvFWxqOTvM8pT+x8gV33yqroIzQQ05Rnj3njVPv4COq18tG8IErRTiDBFEuiYtM1BzieQauL5MocV1wiuEimW6XPAf18/AP+9452PZ1tJZhyvYG3pAAU8OVrDTjx7ePa/d+TYmBpHiBCsTas5LPSe2vavAuMrdzrzx6OgY2yDMMc6HjmxR/783ECdXRmZ8b7uaDkGdtMx28qy1AfMXcbUYG2mQk3KgkODkuBii8GL8RfNqpdAaasqpeCelYdrroZp6gfbypkgEVH6DTA/yyFLhi6BLPKNa6sNczxbaNa7AwLRmXqRd/XqqmpnPR8XZzhxhUmic2PR3yd1d7zqu3s09lmyf1ozhMfKZclwcWi5JqPDhzDJfV4nvrQfpyrmHh/U/QTtlaXjX/++YbTQ76PXsoDyEqY31Cu/s8vmIT/J4jYEB/x+AtiUfRhQ6/zXd32LmjSAZbzcKQI5gbKWN98oyvKn/YRetLVpRIgVrNf5KB0WARM9oo2Yh82UVP5Yr9beIqdAXGRSqwP07nN1cJijYIGRrDUktsmt47AFAzatlFKC/duBjBtzjKfEt65vzRi9nSyuVl3jjkP6iVyEv0Wt0uZVWHPa3IAX9kB8+2D6jTfmId5N2LW9mRKBmM2T9eU4FHVWwFbDy+Vgev2P05kKzlg==
  template:
    metadata:
      name: ghcr-pull
      namespace: barbu
    type: kubernetes.io/dockerconfigjson
