---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: barbu-db-app
  namespace: barbu
spec:
  encryptedData:
    password: AgCWBrKRW2XBvZVM3Xb6ynkKJAwdnxyz6OD9KtdLfd6x8ARi1wmC2NPpiF4TJguA4TcLQdb3g9Loz0AjBtA8e8T09/kZHqaMxJVNKBzB+LZGhM/Fe6wfdTKJ9Aunq5Oi7QSY3UQDQhbmLYWDYs5DIDwepbp4FNDAeGmT9p+wFXe1ru8CRdGFYIxBd5Vyiq3JybpGDAuWXkybW7hExnCVhXjXqABzaHvx3UoZsN92WgsSadRVMrkwpjelaZf3dh3zHv0cYeRPWdLqC8lRzIIyh6ehSBQjx7vZ8g1gtMp+75/pP/PD9hvK+srvuxGgPrYjU812Nk1GfJnoLI7pBcfx7L6C5yjXFex8I77xSTY9JeVpyVA3b+ej2r2ru0t6mgNbKl8XmzcBYY119f6VVx8aL1kFMTGGaTkRgxnm0tXGS5OJrCeB0I0RM5JLJkn/8VeI+lEr4hKrIG5eXMN+JqNRpyKIxJ7AV/4684iO7JBmVBq/poX/X2IyzaPez8kfzgTz9fn7Kooz93QH63OKDNf0VtfBe7VPjHL9RTBpsIM9Nj26kOyqjueVrS60PgNBKwNz/gxC3Mitymlr2kh5SDu6XhwVIFBwvHZybT+PcRDo8cydYwLONxmmEXS+gbgtmC3OnXUH6VlUaGCvzyGZbCRrIQI9MN0jnipOqgTEPO6cs/OxcTM0AalRyAhHofY4yKEsWYuXoDRHx/JeQ4Hvk12M042bLszNM9RteMW4Qij6H+W+bQ==
    username: AgAjISZSjoKEvzqhWJxmsXPUMM0IGUlwG8Pi69tiglMW9M8CALcElGpALfSs5XLmk6ZO0h60KbYATm1SeNfCB9kH3gTCf1P9tG9CWnRjKE1KAcQUzMQgpwzYUGDjvnXomgP7SH7/WwIpz48U0VEJVBDOjqk54Lp83z4+v88BJajMh7ksDLwOh72uv3mhWNr5LomM5osxWOXNWzxhTcLz7PTp9E2TXxvIYs6K3zk3hpSdZ0q73oFO0cIts9iDC9Sz85IjLt/Fl7z4SAmYqNUfUo6atPknXCcA17DekorKXItbm/FNFeqL1atfFJcsLYW6ysbdTUFkQoTsZQqt1JtRLBVPhY2/+e64XriVGi73plgA2AdiKJJCbE4gdTEsXIv98TDqKs1Lzo7D3mSMyKrE8Eol9pK/aKm9lgnPk95SeouPme3z2P3xWnQqCyOGODDBuK/P26ziSdREZPo1rR/zpzmKs96I+p8+3Duyz2X16WLPCq4afRg17AAdb9zhvobG4e4w2ufLh7e2E+jWkfmSfHZZyLoereKxRwNur5hRPOgH5EZiBGMprvnsflCjwjR5/Y8huGs76pHdngossjnzhVx2KlTeuWo7dKhpgZqv48Scq5p1ePEi/p8DUJOZGOo10jh4i0OFlIKMGLVLdYHVt6I9Ng+YHg6vQTU7YhzbrPTlDmLy4bH9kjqwDWTnVGf7T5uc/cn/GA==
  template:
    metadata:
      name: barbu-db-app
      namespace: barbu
    type: kubernetes.io/basic-auth
