---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-ro
  namespace: barbu
spec:
  encryptedData:
    password: AgAxRXBCHFFK5aZ5iZjfzv6QMfzgnII76anu+2fphCKSEcvDiX4jl45ngU3GcmZmDfgUrK0CwHAsOsIuByGhYDY8uRxFfeGcoIx4ifM5E/3lID2a34rqa5eNXTql+ncAmPtDogRgGg5eVTnaOCVOEPbztrjbYIvho4BgFXsixlyQkhvvkkzSoWaSCyxMC2JcPXfH5C8vFMeiLmaHMZza2jSESpTr57f4hD/P9WVEmwt4qbDHoamY5p4tKr7kRB2R3Mar2CYHXirpLpx0eZMIJ97E4MB5L/LSn7R4t/5jhqIN+KUZ+7u5/MMZp70oMo1rq6Z+VCuzZgFxYQhAR4SmhUzRF2VH/A4F/su2+8QD0UR7b2Eb1IobwZmJVlPHPKL/fCPemsc1CCIWphD+OHIPTJHikhtwjQkjxYAI8HAO8lcMNY0RCTS2SQ8KQ1LMNZY/p7MT6szyUsQCnhc87geInEuPqpPym/LpK3FhK4IVOm8f3Kol++ZX+lLnMr0JsV119R22qaiJrkGIEFG+2wyf6iQ2c48elTJ9hvvtwzID/6w04ZTEjvQfO2LtycEk/T0+NGmv+97dX1MkDKv6DCUdto5Woqlb7EftB52I6Hdnq6SF9dS1+hHpJf/ZBWDCWL5SQNJcPOJxD7Xzxgm5iZj/0K9wqF/ZrNIDSm8FkDojyfdSYhgXT5FJhavHRq9olq1JYC0mSbfH/C8exYMC5fvkhkSZLr+fZtADXHu97VCxWQmSbQ==
  template:
    metadata:
      name: grafana-pg-ro
      namespace: barbu
    type: Opaque
