---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-ro
  namespace: barbu
spec:
  encryptedData:
    GRAFANA_PG_RO_PASSWORD: AgCmWcAja8S+GMw08gILhVbWrtR8oqGTW1W1J6CDq/ZdwePkxP7XXWYX8BIMx9/kMisxnVtVGce1T1m6FLZu8X5awYfUaoIPBZgPhaDog8nnw0rQXMswSLeWFi+ciyiCt+XmE96CKj7sBPLlUJMRzrkpNKQ3tLboBpxp3qfuBiJz7vEjkhM7272PBni+xcP6vnRCNdJxdIHaTVtGDz/6bV8V1tKTNZ1mjSi0B9C08Sg1HKlCNkgUgopyPzzCogNuzKs9mqgfCUAI0NePTlyEXrVutzvcRk1EqXyLHZk6ygIaP6YZerKh/Qgsf16CC09ohn33VkUvwWsSi8AVYSWLrOADpum8v0yjPBrgzKA1cOii28zwaZcCaToBerI60BDdpg4x8fFoTahmSJIf6o4og0Nsqy4yoDz1NeSdDdj4CxlWMZQdQqMBKiZ67dImmEc6W6hOGcjV7Qopieid3c4mePMFQNpIKxv37Ga47a0x1u6O2cUXwo+SFiXkeghg8+lKkagpiFR3truZ3ibmOabk9wUNaDQpwK/o6o5EgG1nNDJI0waDCamWMNYogPlKsaMhGMng9ybsWGFdfeMXGWFqACT0ZR0xw5Lr+4aH6nsAFOiLRyBBNkztsVGm3+FL+F3JUlU94x6Nmz+hMxSAvZ9gckMVAy0xKhRTreDNCSN5X3ofzk/D8EYc9zHUI2WhpGFrQysyFMG5RcrzH/iMzU+qGL9uUIgGrhB7BWe3PrGqIU+Jdg==
  template:
    metadata:
      name: grafana-pg-ro
      namespace: barbu
    type: Opaque
