---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: barbu-db-app
  namespace: barbu
spec:
  encryptedData:
    password: AgA20dPIgLuOZxal8stf50m45hpaQcp57HmhSC+HzNTHKx0kwMBk0VoGF2MkSs1KDmXtG9lBbIpmusLAzfFaHdH73L43ukEnePaRweoE8QdTefKQow2j+epworrS1CICRk8346R/78S44wn+MF/VWAaONPHtcP/I8Kii+ZjtUYm7OjwvcFOPpi0it5u0J4f1XEbfkTa/dNXtvJ6jq0Hop1LmLlG5CgfVkPFfTcFwJOqvbf5Z3zXbigsLC3AV0oDgc9rauCkfGRsAh8WON+gbPUq0PkFHUHOvxx9U0pYrtsyxQUyg94J9l1UwxyMl9TbFHVJ0RYfXCWDCcBp3oCk33DOm47rCxwUAjT76gwNV+w9jZgedmJb+NcwqP286labpITa8HSiPHA9QSzwl87EIT/4LDTdWgyi4dx3lFQQNGLPnIqleXscVxEGtjClE9qrgBqBYc4Q6vxgHlUaIy6DUOKRbjoxJnRm0I3pXBJQ5zgDs8D9TkbtRM74gV22lxriheUsVWjfZ7snaHt/I7WPfAWMzizmo4VtAM4tYpmF8rrIDVG4Hn6Bqe9eTwFSRqnMS/+mWPXR/pwMIY0pY43gpXeDVT/4VRKrQkZcCcTlrPYikdB2isnphzwLIhnvEDZJri3RoalhmqWhzxaeDWjwiP9/C8AaWYSmzLb8zQMK38deKLjDUyqu14DuBhFtwlBh0m/DIXDTZL6odD22r8lXn5lecwQrJ+gI2Tsk+QCPRCUg=
    username: AgAipNy1GrXtOyJ/aJ7W3bzG1vyqdsO7ffmB6VoUsHGW6NPdZV8DS6cZN9/psbmcEfaF68aJAb3975PdR3AMe+Le+aD//YHP17e30HFJHuO38mi4wWgi3hOMDUvDo7FjnBbezfoSp1TEcMWaj7B0Y8NW/c/hxQmXUc9UbwANXLdFgK50owqVu93wQQa8gfm6BVBBJYT+6Rqetyzzam9NQZEO0vjZ2dNu3g1gP1g08aBLG3p6Vp/qMh19JLYNLpw19gE2LL9oI16DO5AvHZ0TDFmiOdKtm+dwskJNXyN9J9xgMG2/rslP2aSlYOtKg5pZk27ACcR6pkEO1RgyaVE0tCgfuj03A3QwS/b/jU8XwEVa18H2Aq4qubgccv7bQN+5FaylGBygw164uJlia29cKhJh9DmujB85uYcgjhcKCj2xjk/t/QwRd8QLViT0Bz0GbkC/96SliMVYbvfud0FpXcxRCu9yikw8hCZH7Izm1eLP9lalZGqQ7beO8rk9cnV8D8a8nnK0K9MbbnCjmaucK3ZaR07vuaIPe1xj5WMYqFPxBSAtqYIfrKQ+qTdlzw4afYnCAIKlDgB+TBHrhD2G+fA9Pn41D07jZBJcFuGjIO6T80mpn/wqmqImB7yb8CLlHYjaZqubSrlL8utc8xBt8ad0dHgRRShjtfn+PmAXP4aiWvgUOsM7bfLphTwz3YmHCkA55CAbHg==
  template:
    metadata:
      name: barbu-db-app
      namespace: barbu
    type: kubernetes.io/basic-auth
