---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-ro
  namespace: barbu
spec:
  encryptedData:
    password: AgBxl68k75BfFIiKt7fkTqEkvSHcV4QfZzgbDrFkgLznQjKmx69I/2SxgLYx+evEaIxKPC91dBAkROEio1PL4ZXKeeo9q/FRChjIePI7HJurplCYcytkq+1HtblBzYsKJ0gNbVBEDq9TyO6TOeXhAPA0yU9Nsv3Lbm6k8KBE/xOTxTi7biqBP0X+Peu6dh3h5LNV7MyzHW5FGI8DZgkyjJ5i44wWx45px7sXDajrVMYBbr7hGyvSjKbN3kwwJZ068glI/x0tz5l4ysh9lFqyydsM1TuykUS+IDMO5HTJAGEsUXg9bz1U47QH9yua1fTAcLgAGYl8t8E0DWIuGb9fYW5ClnCC/bdVDVXhg3dJZXK4ZnT7RzyeCaUeFnpsdJYS9BnoPVMOiuPGFP3GzJ0AzfoTBDZv1Oky0l5ya4h/MAxjElMn+yFXEWnkTlzOUxYDtv4XDTZDozqY1O4Ab1gNhqEpnKMC5+/SYSLuJd+QynTvjGBKYquOFBZjZMzwKDimm19SEczYac6RlElf8sSTgYVSVKVjdW3k5qnmkwn2f1+MUysg68DEsdxIsvsQhfXOPAhtlUa7IjhHA895RZItf1aeMDR7raYxVvCvfAzucw1pjUX66UJvUnXdF9XZXPWgBMK2cvAMua3TPXZx0EX/ZFQoIRTDpmFRuYXljbM5UJCbELO2N2m1kAWbgFmFMz8ueYAOdygXCpRLkNZWIRRtINV431MKuy66kMfVr4m+NK28
    username: AgBUtS8bo1Xqh+IoLBcE3QGRCmaqZaykcteQsW3c5bsH+Kf5wAvIWw1ft8TgAzwIUTQpHCKrlG6WqBIrrffZsJjTj9q+H55Bed4OKnF2cLeu090ZlS8yuIIetphmJiYuxqRCLHGaXMTyF/ZP+a3DxdPf7dS3pGUVA1Nns5VfVTn6CJVEmoeHcUBJkkHWguiMZj/qSP72q/371+XEBZP6Vhe1WgLoX1MH9ntzU01DGxWZSA2EvFRiT8dcFY0HsNstn1dRyyinvZVVyptdxRkuSLfu1c2LciL20w1r0iFpEHeWIgsoRP+p16fjw7fzavl4jFHsvcTx+IgAAQMTTSvCyvMmFVmDeCxiI1D3FP6OKIZPhk+9IEVtMGc/5X+k+f7YXolgHZF80XPhS2n89pj77Xe0slM0sPSL7WCrLs6UbBYlyoK7X9q+PFgypkkKGImAu1arar1iVdvHxUnQxLUXhvOs4DyGtwg5T0cJb4+qY2sll0qSh/ST8J17K0pG9VL46NbPVkSnrph7JJA1bE1tDkKgY1SeWlsf4g0qC7V8e+sY/JdFZiCHD3YlJtbIOw2wV9+e82dgZB6zya3AaJ6Sh8kppIJ9ha2UiMM/ydcK/QQ1sm5ySsNiaWBUG15XSY8F6cfR5BuD/UY1ByHeLYjmeCpAHlT6BrdtgmY7C+c7J7jtYKTN5WQLP7WWsV9oranxtzccC69bz/2jUxUw
  template:
    metadata:
      name: grafana-pg-ro
      namespace: barbu
    type: kubernetes.io/basic-auth
