---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: barbu-backup-s3
  namespace: barbu
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAXuIJdHjHRuu6tFps0LdXHSeTpWIcFaDkjYH/2LhbLslKMO46z/oMZJNlZ9+EcTP/G9XYf/N91Drgt5i7BbL9bko7UHWGO6xKKaq9tVDHRZ930/D/dHa3Lq8uUkA9pi9XVB7z/Y8IeQ6UoVKqQpVyIbRLTDX8zpTG6tuNQUFHo/NyZs9vYYv6Xmi/+Wfi0d13BF9W1j5TdDiPALXIPxsyS7CIFcsYzJVT82UBBkI8GrJahmTTS+5w6ELKhf1AjI85K0iVAYRQ5S1qDgVW6CKsxr74WzPBmnvJtPh3NDC7mqLSK/dfP/0X2skwkhTtLx29MaSu+ZAdV6pJDalqEQr4yM0+I54VjZt6u+zJDPa/znYaFVrH5tKfA1CnIWh7vrDpV25Vo9Et3QLITvf9zc8LgDPirIbY3XUKRDvr6Yg6q31LeRzEVqyu4YB6b4xOj+2RUrTH+0XCVoAgyLx3jvPdX6D9+SVdCWVtmwvZAqdyOUIV9Sv7YSOrg+tb8ySyF1Ik4147h07RhYnaPXa1oOB4NDF8EFuOtXQA/Ed0v2O1NKTHnYSZeOPf6JuNasS/HxB6Mo+RWuQyXF1vib3wDVvlhlTHyaM0nbRhQ5OWfdmDPrxopub7rARWpdBzVveyByp/IaETflTeAMBL1CYSGYpRqVKNiZ2bbD5IZyB1N8nmZdIwWd+OFwo+HrhdIRtCZgwxh5gZOrTUXJf7uPdYqKmI0KdNqzg==
    ACCESS_SECRET_KEY: AgAoV5vy2G9eOzsBUZHVV+Bd2gtCzMJrUXvdKwLmK5qL64/U/02iqQwv3g1y61vmvy2JBZdeghycyan9K6ahPbOKwcVbFaoaDsIrTJxYlnvuBHECpjV7nByxWf1+lF4Jux6nD0l4jyJMQNCuQp5Ig+kr8O9O6huubHwFOUG2bGPuBt5Eum5XZfFgcQ9k0l8NsHlSBclhehD0Kkx86ZBdV+/q7g9bW3LXgMHaPP3w3Sq7crAdLiHzwVndJCSouhLgiXWk2rmgdEUhlXlXI820Axkvb3KgblZor7mVHwQFsGpRzC8QtegSnYODgkptbXUKGFw+eOsI1iOuMOzWwqwfaFcbTPeacVVXnX5qcIOx06NU9FeFKsZckSc9nNpEfC9ReAQB/9cP+O1MYBf8btxtW1KvjbW4bSMCqbsbViv0+JWn7WUYiuFL/q7vkeHrSQznEGL3tg5jilX9Jj6BYBTJHzW0X96o0iV5dNx10WhQh2ydAk5uVMjQyYFqDk/VIGV5RcwV7+aHhSVhoHwNorcI6KlkTD1Wl1jEFeaecXTk8oBH5MZubBdLob4BJh58x2IJAigUt7/GnXketpqrbsBau2YXxn0cn4SR7NHoNDoB5o8oqic+YEYJLA4xsTXb6R7dxrvqoEynX7e+nbjlEgDKFfPOYyjlV8Gt4Nu43f2bwcfNa8et+m6fc1+lPQWap7/SvV8uRtNGYtRrcWfNA1FdCpk3sTFeu9Pr+JnsfUhlRDXvZGOlg89igHHz
  template:
    metadata:
      name: barbu-backup-s3
      namespace: barbu
    type: Opaque
