---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    url: AgBQLM1cDHrclAHxYPYF8ZKXQnyhxy1YP9Q4LCxT90UpR4lC7m5g/gMo/QpxJPE9L4lCLE12zaveVjQATHK0kam3q+jiCcxIOx5QlFOrIXD9xw6RysYfip+1OmgkasFflo9ufR0SAiJF4GazqjZD5K95beO1qD+dyz+HnHnPeOMBi52Z7MriFDJu8yIbca+Y/gcc1gs6GhyrCz8vvL/c9OE8/3bkLHAi5LGtWDfkDdiNguTFfKunF05vkhCR33L7ePl2852kqFw28TCPH0g/6aOUkwejFJLi06NtysFMZIWvcyvO29tDFmCznsLnlZT7MlmYfbQYotZnIr8nML8HWqoDneorwIs7T5KU8N+xXfi/OYY2MELN2C2nixMzAnTHa1BYi8IPo+yJBbs0e6VB66pPztxhCm6zXGsk/3S0QNrCqE/wzciLeh+e2v1OCHFKdHpSVZxE1IwInIFqj9qPXJcOUOxFRdHz0w02Z3nCDQ/VeE2i8oNKUcDLzHfKk+J3V3vkSijrkkcb5l6ygQRUz7gHtK16Ux/Y1LvbCtXcOJE/AN2WtbhL/04uuJISa3HtVdkWuP+gGXGZKs6nN85DDGe5zOZCHxJGCRrnIH3hT8dpGSna5tog5Hi5T8suZ2MJs60K3x8FT5uINwJRhutVEY3E9TAksuFWDrRtVp+Nr0G/EW+ewie9AAEIkAOAYi2wMU8MxYV2lN1cx0MNSepmOL970kn95rAn3hrbSvCQY5tmE13yCTCLl5IAYmfdDosEBlCj0752cZMcrcUg0gEPH83L1oHi2tC/phJdM+ZafLEaTv3Vhakr7CUWIZ//dN0z/iWlCQw/OJ0eZoQPoLfBrqQmOsEF6JvyEt7Y
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
    type: Opaque
