---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-ro
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_PG_RO_PASSWORD: AgC7WRyvQRdUqJ4DBd9cyuX8D5CoGX89AoJsitSnMnaekMHmRnzWLiZvc0SIGJL2dFHRbOU0RywS3IiN4drnptbHSDnEk9wrMwfMD0AMk+pB2IRl0MF02BGXjrDoH6X6/4uX2J5SFgVkyANms1LCgbGOrfVGX7BEeE7osv5byFE3L5vSUPeoZuQiGi8Faa4C/DyOm1BlzW/U+s/3gMEoC3yl/5a1y5ZdIEqQse+jLAIj6v3j9DWFyxSbTF8XypBkOCzuGtqG9rLyaayEsN9bikNbQ8NMSDO2aFMMctOY9IFTEq6Yu/SzhoNIBbucG9qbcYzrFjTX+0g9ysbWtEl2VSkVmvqNg++mJmiY3MNABNk2hUG0jg+F1gw2YejLKyizMAWVOW1vHzyBO2Gu40Vv07je/cJKxv4t8YMrW/3+MsswPDuLeJ+HfG8XmOK/V6ZpgmlwxcM6Xd8gnw8oCInBYMjTk0ZsBrKFiLMZF9suXsHHEiVf0qPxAAEWHa/w+DKwW+vpRGVpMklldWzwfTg4yodZREfrL1bEFi7omLnmIVRkeVOgiKKbqdJhU5fmfIRxv0lfJU/gPfMaz71qfEa29OPe9QDozTxremCBXUATC6pWRUdxn+Pr0QgrlbXvr3bzvwSHaf1FRX/MRsvDvabmYIBbgVFlMV+psbxAuTB5wBhLRgmjMc/f+deq7ZtRcfcZDl6VtH4mHD7/dBXkXqAuZ7kBt8nZ3QR6QwVniwwCKirvtA==
  template:
    metadata:
      name: grafana-pg-ro
      namespace: monitoring
    type: Opaque
