---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCdhW06x2vhA1E0ztCfEwBlSJXN+7Bxylq2RXHviQqVu5k5D+pRU/yQNoMiciM5iGtKAELJ6ej8ZfwdL9LYI6s/2b+lAjBkh4nZamKdro1MXgxsMwTvp+DEiDumOFz0nbSSn6lQnMyDhPk3DsMbXFNYKSeoOSymb/nJbRDMZl1JUeuVy/LFiwhHrCDxkuEGqawcuerBNj7x4QdNz/mKCp8bpFe94j2bYZiVHZm1n3XdhEbtqrCJU1mwaEQBqDAdJKPJS9MHF+u+PxDIdV8Hg434wCsbD1+BXaUhflvIIj3t+gHezswa79w1otQpgszJX6T+D2lFQCwv5JLfJB0WrfA0uoW3uSC2Jsyw+f8I7BNkYs4Sp7UxX+gOd0DuYvcNpk2jx1Fwsjo+CtQU+yDQPfzVw0x5lVSaUg5tF+XEHhNnnBWlad3R1JZaIgZUT/+Hl/Y9fXu2PA5F1FGjCGNcHXXBcGEoO8LbFn52BWKjUakjKwbnoxhVsrmzzX0VvueOrLL0CmJdtTHw8eRr+8qYLHloy8Ib2snrqb+cO/9iXOZ1BtOf8hLV0ZLY/fkAcw1jI4AhxOLjQh2GtYF5NGbDtpJ6O7KKeu4liRM2dc6Edf6D9Ug1lofXNfbKT8vxlI+riitZlvl69+VJ7W4b2deaIdrFndYqtkVX21JnHLJMvBuh1uKA9LuwfptFaa26vpKkNlnhCQUasllknHRuXF8K4nnvfodI0NI8Qd8ZtGEWs3g=
    admin-user: AgCa06cDMuOAyePZId+Om4+zHtqa+TRcvnr/GjBOZ3mKF6QYqQrmw6TXKqz/HUaA7S1vZ+bEp10YfkeST0i0MM9y9QBn45IBfqsCH1sAXmynzC/i8XG5GLI/xPoLSdpQT8oEHgeFrZZCLW9DUPf4XnaIGFFqG3hG73SRFm3oQ7kPIxot1mZWdg8QGm8zUaPmqFdD2DKyNNZjZZjiQCB8nN9sSJ8oXkFRp5qXVXXYChRZDtWv07c1EKU/uBX9oUoNmkEqsczqU/FxUorJJ/TRacD1p3JE1WZx5PZ/tqL8+9yObRfKQshXiq+aIwREegGDyPHdcD6TLioWaYKGnlK4Eijx+AsgVeWLA+LYrUb2LDuKtjIIdO59O3TOXVY0e2FwJOFe1iBLRjAaUYTov0rQvlSDeQcIpIOEAMpPYOlENO0Rs/0n24ePwfbhcKSFaDP4fQRVGTptHgVW8Cz5mL0PeXOB9NLfvKl4jsd992pHHAr0rh0nYBhCAyCWcu3JY27PmqfX0yeklRhD5QFf+IMVebM90rdS8FoRIpxWe95A9qiPyhxP96xo+X2i2WPk5gS5P//4J0IKt1IdpGJBbJBvPtw9/VvgZMSotHKZZEedo0MLwSTE9mqPeD8iuwKQEwftOTo92TuuHQVT5WUCKoBuG+1lyeb1m5vBSqj92veYhO5seDWo9VxVExx6QjKnjGcr9WVt3ovlVw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
