---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAZbfi8el6WOnBHKK9ohZgreWEo4GKjcjSMtGsj5E58wsVIK7wke8xMetGnjUP2jU9yGOV2rdzxn3NzhcM2fFdwAA+UJYlXEVkJ+cOWLtCyh8QWmGjDu6nXhBk+kOLDiA1OhCGYy3IpqviH81h2S6P28LtX36mijuSJxVwyUWx98TW8rwh+e87V6LBSRbkw6e5jsjg3fkek3jq2FwH3qP/7Y+dZiZCuaDZx7ohjU5aI2e1+o4VAwAlsAF3yybu7orOZqsWsjC9iNlmhPncatffu2r2aN1O4Pk/DnTIQYfwMlW7Pq+YfuxUVIW3qegA8cUGmQ5q2s3Xg4b0TYrL1NFzobbeshOJcuecGXfAAO9fhv0dqRJE/wPWH7kF0KmrZ6N7saSlkE08IFRV0XhJf2Xuzdjd2BsLem1AlbB55HSOgVbkjjabkYgbronMSZR9HEjHQUw15VpFnvmBw/PtNlArr8Nr3IifJ/G1WN7OLK3uibemnIMWg+9vD7BcNv2bULN6wUb1kPU0itBth7L59pCsVNrfbZ+C/Zko2UMtDhMLRZ+0u9zebxbqb0sESXi3wdVFa4YM9ORKYmLM6L/yafF9L7VQiENzNvs9kOblsPWW8XDtBa/hCdWBkithaCcC+hgluHdbWRyml8MOkUr23rvTkg6HpVo3N+F/7bsa62huF0mxNnr9EUAkzWu1PKUT6zSjSP2aymgyw/XGQBkVRwqQhHdTxhxer31SkIN8qSNglUA==
    admin-user: AgCHQ1nAgofBUzEBlwZoJSXdkmAXlLhA83FUxy3c5hhWdqJB4UZeIWnJqYLgEyPRs9kCctgYWXdg/HqJmcqyVTTzZcopSBm2EIVxF8V/ZKVTr34sPLm4Q4M9LItNMcIS2ZR1HrW8BCmcUqddfCza8hQadUbc5iJcMO8GZnNQEwFKUQsDdnVOQFPaIonSCVxS4ransQvGv6Z5mkKnl57DpajWxSI71Kq3Tl7ayx+HBuSgX9LJInwKXE1bbLN7nQKL/XSWVe60FcT95Wtcdu5ZQnnK777JmXg7AdDhQM2Aba+VAY9cWck+GliSvNyBnoqWsQNi9Wk7rzOcvfQ26dmu5Cd9l0IFYoJV+WDQhcJmuHNrmMLev74MOL+PQ6Ncz7YmWTmuSqi7amGZ5tdN29kj/MKt+WNxhc74X4ReaTlUWikJwc4TSRNeC758qYDHyFWFM6922Ttox4j+NgFypSMlWX2e+2kQvxC0y1RkViUjIECTVHgbI9V+xDQQ3N8DoUAmcsVx2Y1GRKXoZUxhcAO8mAw3MnW2cw3UCExBsdFSIMOSjoUG6+PTxaGiSQocOHSRYfgYzZhJhRWuLGAYvGi8am5fNWvgx5SBVsIdeEjK2/NDFXcbN+Poul/96Kkynw1rLZBKrfahp+Tubjeon2lmT/4Pjt9PqPxmtVb6AKKgj0ZBF77SNod/p4Pp+UeAVyWgXE6kqSM86Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
