---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-ro
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_PG_RO_PASSWORD: AgB6fabHEW00yk19NYOd/25bsDSemvEzW4RDwYXUhw7ZaTu/NXgyP7C0rbsbnHsNZjLYZ62mD5PDwrM28Hp5EWEI4mS62alQqc6YwOvo7UwdNrTUetUMzStwiKdFw1d4779UnxCFxrjR3gTtn8wttJbH7sEY0ZWU9kSEBi7wrHQG9QX/AkrX03XGp95zzjhpuGauwJxK6mVesAezGP7ZWsl+T4nA7HYy7ROuUOhBEr2EMqLTFLg8RwneQYqnpEPEsHz+h5kvst5hGwCnRjxJkPvmkUlGhpspl9Yd8W3C2/Q2OVcWFCu2orvx8nFLFwbe/Hl1i03OhNZXuNV+PTeA12MuAn+FMgdxXvNsUWeYLWytPABWNsamE0cVx61PQGSJQTylkfE+bhbYf4TI7kqs2zaV4jDzktbV4K6rI117RyDt9GHXprDGHkGRKmNz9kQup33dAX3ndZVA/aRC/wOgH5Ns+XPCwRNJ9cwA4Jigf5hZ51aMPjAN9VfyCAB11uXxDJg7KqiR8hg50psdccRhuYUDDq8/8DsRcgnqvF9YoE9JCysC16GHPl2BJgYCGPxbCuOUwiKx0066pxUycqYf2Mw/sq6PSUVtRN+Zg9rdyUIr0eOXoH+J8bPsIFCc9k3jwrNnG01Nmuv6jBi7YDY4m0QgGjifQSl2YjsbrFs16Bj4OHSnGsPqZT3Fwb1DQ+t8MBHAbOMo1LmyDIezgqX4NoJjSPidzNonguL9WnO6vxLN
  template:
    metadata:
      name: grafana-pg-ro
      namespace: monitoring
    type: Opaque
