apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barbu-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # after the operator CRDs exist
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/barbu-game/barbu-deploy.git
    targetRevision: main
    path: charts/barbu-db
  destination:
    server: https://kubernetes.default.svc
    namespace: barbu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
