apiVersion: v1
kind: Service
metadata:
  name: barbu-redis
  labels:
    app: barbu-redis
spec:
  type: ClusterIP
  selector:
    app: barbu-redis
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
